name: MakeFile_Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Main_Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential python-is-python3 pip
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install lizard

    - name: Build with GCC
      run: gcc -O3 -Wall -Wextra -Werror -Wno-unused-result -o project *.c
      
    - name: Copy bin file to dir
      run: cp ./project ./tests/
    
    - name: Run Public Tests
      run: make
      working-directory: ./tests/public-tests
    
    - name: Run Private Tests
      run: make
      working-directory: ./tests/private-tests

    - name: Upload log Public Tests
      uses: actions/upload-artifact@v3
      with:
        name: public_tests_log
        path: ./tests/public-tests/public-tests.log
    
    - name: Upload log Private Tests
      uses: actions/upload-artifact@v3
      with:
        name: private_tests_log
        path: ./tests/private-tests/private-tests.log
    
    - name: Run Lizard
      run: lizard  -L 50 -T nloc=30 -C 15 -m *.c
      working-directory: ./
